# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

call_apriori <- function(nb, s) {
    invisible(.Call('_rchic_call_apriori', PACKAGE = 'rchic', nb, s))
}

write_transactions <- function(data) {
    invisible(.Call('_rchic_write_transactions', PACKAGE = 'rchic', data))
}

dynamic_cloud <- function(data, number_partition) {
    .Call('_rchic_dynamic_cloud', PACKAGE = 'rchic', data, number_partition)
}

hierarchy <- function(cohesion_matrix, list_occurrences_variables, supplementary_variables, matrix_values, contribution_supp, typicality_supp, Verbose) {
    .Call('_rchic_hierarchy', PACKAGE = 'rchic', cohesion_matrix, list_occurrences_variables, supplementary_variables, matrix_values, contribution_supp, typicality_supp, Verbose)
}

similarity <- function(similarity_matrix, list_occurrences_variables, supplementary_variables, matrix_values, contribution_supp, typicality_supp, Verbose) {
    .Call('_rchic_similarity', PACKAGE = 'rchic', similarity_matrix, list_occurrences_variables, supplementary_variables, matrix_values, contribution_supp, typicality_supp, Verbose)
}

