# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

write_transactions <- function(data) {
    invisible(.Call('rchic_write_transactions', PACKAGE = 'rchic', data))
}

dynamic_cloud <- function(data, number_partition) {
    .Call('rchic_dynamic_cloud', PACKAGE = 'rchic', data, number_partition)
}

hierarchy <- function(cohesion_matrix, list_occurrences_variables, supplementary_variables, matrix_values, contribution_supp, typicality_supp, Verbose) {
    .Call('rchic_hierarchy', PACKAGE = 'rchic', cohesion_matrix, list_occurrences_variables, supplementary_variables, matrix_values, contribution_supp, typicality_supp, Verbose)
}

similarity <- function(similarity_matrix, list_occurrences_variables, supplementary_variables, matrix_values, contribution_supp, typicality_supp, Verbose) {
    .Call('rchic_similarity', PACKAGE = 'rchic', similarity_matrix, list_occurrences_variables, supplementary_variables, matrix_values, contribution_supp, typicality_supp, Verbose)
}

